services:
  convex-osu-proxy:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - default
      - observability
networks:
  observability:
    external: true
